### ISSUE TITLE
"Траты за... " на главном экране не обновляются

### ISSUE THREAD

**Issue by cd-con** [movpushmov/Budget-Control#13]
При вводе трат (в том числе и выполнении цели), поле "Траты за ..." не обновляет своё значение и остаётся на нуле.
Баг актуален для версии 2.2, на версии 1.0 баг не воспроизводится

**Comment by movpushmov** [comment]
Очень странно, можете прислать видео?

**Comment by cd-con** [comment]
https://user-images.githubusercontent.com/61092992/132872507-37ece3c6-49e9-47c9-b6ea-cebe1f36dde2.mp4

**Comment by movpushmov** [comment]
Так вы создали доходы, на видео это чётко видно. Естественно в тратах это не будет отображаться.
