### ISSUE TITLE
Добавить прокрутку в случае переполнения на экране "События"

### ISSUE THREAD

**Issue by cd-con** [movpushmov/Budget-Control#14]
![image](https://user-images.githubusercontent.com/61092992/132866976-6f2fa182-1aab-4d19-906c-07f7424e6e1b.png)

**Comment by movpushmov** [comment]
Разве на этой странице не появляется скроллбар, когда становится слишком много событий?

**Comment by cd-con** [comment]
Нет
![image](https://user-images.githubusercontent.com/61092992/132871905-c399ee30-c456-4903-99fa-3a81533a67ad.png)

**Comment by movpushmov** [comment]
В ближайшее время попытаюсь репродьюснуть

**Comment by movpushmov** [comment]
fixed via https://github.com/movpushmov/Budget-Control/commit/9942cb3fc7d561fad6abaf20d5c3e8e18d33bfd5
