### ISSUE TITLE
Некорректное отображение иконок

### ISSUE THREAD

**Issue by cd-con** [movpushmov/Budget-Control#2]
Версия от 07.09.2021
Иконки в меню не отображаются (см. скриншот).

![image](https://user-images.githubusercontent.com/61092992/132538669-c9a1ab80-4814-4a48-ac6b-91cdbf438b07.png)

**Comment by movpushmov** [comment]
Чтобы иконки в приложении отображались корректно, вам необходимо установить шрифт "Segoe Fluent Icons".

Для Windows 11 он поставляется по умолчанию, для Windows 10 его можно скачать тут:

https://docs.microsoft.com/en-us/windows/apps/design/downloads/#fonts

**Comment by movpushmov** [comment]
P.S. добавил в README раздел с FAQ, где расписал решение этой проблемы.
