### ISSUE TITLE
Данные в разделе статистика не обновляются моментально

### ISSUE THREAD

**Issue by cd-con** [movpushmov/Budget-Control#4]
При вводе новых доходов/расходов данные на вкладке "Статистика" обновляются только после выбора нового временного периода (см видео)

https://user-images.githubusercontent.com/61092992/132643274-8f91cf2b-112e-42ce-b0d9-6be8e252eb31.mp4

**Comment by cd-con** [comment]
Это также относится и к разделу "События". При закрытие цели на главном экране, нужно повторно выбирать дату, чтобы расход отобразился.

**Comment by movpushmov** [comment]
Проблема ясна, сегодня разберусь с этим.

**Comment by movpushmov** [comment]
fixed via movpushmov/Budget-Control@b7a74b36aa22d8407eaa8c6302f7a26b11af207c

Пока костыльно (просто отрубил кеширование страниц), но жить можно. Скоро надо будет переписать хранение данных и вынести это дело в какой-то общий мененджер.
